# Generated by Django 3.0.8 on 2020-07-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacton',
            old_name='time_of_transactiob',
            new_name='time_of_transaction',
        ),
    ]
