# Generated by Django 3.0.8 on 2020-07-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200726_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funds',
            old_name='current_blanace',
            new_name='current_balance',
        ),
        migrations.RenameField(
            model_name='funds',
            old_name='previous_blanace',
            new_name='previous_balance',
        ),
    ]
