# Generated by Django 3.0.8 on 2020-08-09 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20200726_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacton',
            name='time_of_transaction',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 0, 23, 53, 429501)),
        ),
    ]
