# Generated by Django 3.0.8 on 2020-08-13 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20200810_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='funds',
            name='money_added',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='funds',
            name='money_removed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='funds',
            name='previous_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transacton',
            name='money_saving',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transacton',
            name='money_spending',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transacton',
            name='time_of_transaction',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 3, 20, 35, 167152)),
        ),
    ]
