# Generated by Django 3.0.8 on 2020-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20200817_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacton',
            name='time_of_transaction',
            field=models.DateTimeField(default='2020-08-17T15:21:33.333078'),
        ),
    ]
