# Generated by Django 3.0.8 on 2020-08-20 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0007_auto_20200817_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_saving', models.FloatField(default=0.0)),
                ('money_spending', models.FloatField(default=0.0)),
                ('time_of_transaction', models.DateTimeField(default='2020-08-20T19:04:34.229743')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transacton',
        ),
    ]
