# Generated by Django 3.0.8 on 2020-12-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20200820_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateTimeField(default='2020-12-26T01:54:38.904248'),
        ),
    ]
