# Generated by Django 3.0.8 on 2020-12-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20201226_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateTimeField(default='2020-12-26T01:58:24.387020'),
        ),
    ]
